name: CI Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y build-essential

      - name: Compile tests
        run: gcc tests/test_memory.c core/test_framework.c -o tests/test_memory -Iinclude -Wall -Wextra

      - name: Run tests
        run: ./tests/test_memory
